"""
foundation/ — Pure trailing indicators.

Category 1 indicators with no event semantics and no structural dependencies.
These are the same for research and live pipelines.
"""

from src.indicators.foundation.ema import compute_ema, add_emas
from src.indicators.foundation.adx import add_adx
from src.indicators.foundation.momentum import add_rsi, add_macd, add_rsi_divergence
from src.indicators.foundation.volatility import (
    add_atr,
    add_bb_width,
    compute_atr_ratio,
    add_rolling_atr_ratio,
    add_body_ratio,
    add_volatility_features,
    add_atr_features,
    add_bb_width_features,
    add_realized_vol_features,
    add_pullback_vol_features,
    add_garch_features,
    add_stochastic_vol_features,
    compute_rv_ratio,
    compute_bbwidth_ratio,
)
from src.indicators.foundation.volume import (
    add_volume_features,
    add_volume_baselines,
    add_volume_flags,
    add_effort_result_features,
    add_delta_proxy_features,
    add_signed_tick_pressure_features,
    add_vsa_features,
    add_wick_effort_features,
    add_volume_ratio,
    add_key_volume_flags,
    add_candle_delta_proxy,
    add_vsa,
    add_wick_ratio,
)
from src.indicators.foundation.session import add_session_features, add_time_features
from src.indicators.foundation.regime import add_regime
from src.indicators.foundation.range_boundaries import (
    add_range_boundaries,
    collect_range_boundary_debug_tables,
)
from src.indicators.foundation.value import (
    compute_anchored_vwap,
    add_anchored_vwap,
    add_avwap_from_last_swing,
    add_asian_session_hl,
    add_prev_day_hl,
    add_prev_week_hl,
    add_round_number_flag,
)
from src.indicators.foundation.volume_profile import (
    compute_volume_profile,
    add_volume_profile,
)
from src.indicators.foundation.sr_levels import (
    add_sr_levels,
    extract_sr_source_events,
    build_sr_level_registry,
    update_sr_lifecycle,
    project_sr_context,
    add_sr_research_columns,
    SRLevel,
    SR_STATE_INACTIVE_PRE_LIVE,
    SR_STATE_ACTIVE,
    SR_STATE_INVALIDATED,
    SR_STATE_RETIRED,
    SR_SIDE_SUPPORT,
    SR_SIDE_RESISTANCE,
    SR_FAMILY_SWING,
    SR_FAMILY_EQHL,
    SR_FAMILY_SESSION,
    SR_FAMILY_DAY,
    SR_FAMILY_WEEK,
    SR_FAMILY_VP,
)
from src.indicators.foundation.sr_range_proxy import add_sr_range_proxy

__all__ = [
    "compute_ema",
    "add_emas",
    "add_adx",
    "add_rsi",
    "add_macd",
    "add_rsi_divergence",
    "add_atr",
    "add_bb_width",
    "compute_atr_ratio",
    "add_rolling_atr_ratio",
    "add_body_ratio",
    "add_volatility_features",
    "add_atr_features",
    "add_bb_width_features",
    "add_realized_vol_features",
    "add_pullback_vol_features",
    "add_garch_features",
    "add_stochastic_vol_features",
    "compute_rv_ratio",
    "compute_bbwidth_ratio",
    "add_volume_features",
    "add_volume_baselines",
    "add_volume_flags",
    "add_effort_result_features",
    "add_delta_proxy_features",
    "add_signed_tick_pressure_features",
    "add_vsa_features",
    "add_wick_effort_features",
    "add_volume_ratio",
    "add_key_volume_flags",
    "add_candle_delta_proxy",
    "add_vsa",
    "add_wick_ratio",
    "add_session_features",
    "add_time_features",
    "add_regime",
    "add_range_boundaries",
    "collect_range_boundary_debug_tables",
    "compute_anchored_vwap",
    "add_anchored_vwap",
    "add_avwap_from_last_swing",
    "add_asian_session_hl",
    "add_prev_day_hl",
    "add_prev_week_hl",
    "add_round_number_flag",
    "compute_volume_profile",
    "add_volume_profile",
    "add_sr_levels",
    "add_sr_range_proxy",
    "extract_sr_source_events",
    "build_sr_level_registry",
    "update_sr_lifecycle",
    "project_sr_context",
    "add_sr_research_columns",
    "SRLevel",
    "SR_STATE_INACTIVE_PRE_LIVE",
    "SR_STATE_ACTIVE",
    "SR_STATE_INVALIDATED",
    "SR_STATE_RETIRED",
    "SR_SIDE_SUPPORT",
    "SR_SIDE_RESISTANCE",
    "SR_FAMILY_SWING",
    "SR_FAMILY_EQHL",
    "SR_FAMILY_SESSION",
    "SR_FAMILY_DAY",
    "SR_FAMILY_WEEK",
    "SR_FAMILY_VP",
]
